"""Keeping a plan and an execution from ever becoming the same row.

The bug this feature exists to kill: `trades` accepted rows from two
independent sources -- the IBKR ingest and hand entry -- and deduplicated on
`ibkr_exec_id`. A hand-logged fill (MANUAL-<uuid>) and the broker's copy of the
same execution (IBKR-<transaction_id>) had no shared identifier, so they could
never recognise each other. Planning a trade here and executing it at IBKR
produced two rows for one real trade: double the position, wrong average cost,
and phantom shares still open after the real ones were sold.

Four properties carry the weight, and each is one careless simplification away
from being a bug again:

  * A plan is not an execution. Creating one touches `planned_trades` alone,
    so nothing about it can reach P&L, win rate or exposure.
  * One plan covers EVERY fill of its opening leg. IBKR splits an order into
    several executions -- this account has an 11-fill entry -- so attaching to
    just one would describe a fraction of the position.
  * The journal values land on the earliest fill ONLY. Prices replicated across
    seven rows are merely redundant; `risk_amount` replicated across seven rows
    is wrong, because anything summing it reports seven times the real risk.
  * A plan must predate the fill it claims, and expire. Without both rules a
    forgotten setup silently claims an unrelated trade months later, and the
    mis-attribution looks exactly like the feature working.
"""

import os
import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from types import SimpleNamespace

import pytest
from pydantic import ValidationError

os.environ.setdefault("CORS_ALLOW_ORIGINS", "https://trading-journal-test.vercel.app")

import main  # noqa: E402


NOW = datetime(2026, 7, 22, 14, 30, tzinfo=timezone.utc)


def make_plan(**overrides):
    """A plan shaped like the ORM object, without needing a database."""
    base = dict(
        id=uuid.uuid4(),
        ticker="PANW",
        direction="BUY",
        quantity=Decimal("3"),
        planned_entry=Decimal("336.00"),
        stop_loss=Decimal("328.60"),
        take_profit=Decimal("345.00"),
        planned_r=Decimal("1.22"),
        risk_percent=Decimal("0.89"),
        risk_amount=Decimal("22.20"),
        strategy_id=None,
        thesis="Ascending triangle, higher low.",
        status=main.PLAN_OPEN,
        created_at=NOW - timedelta(hours=2),
        updated_at=None,
    )
    base.update(overrides)
    return SimpleNamespace(**base)


def make_fill(**overrides):
    """A freshly imported broker fill: journal columns still empty."""
    base = dict(
        id=uuid.uuid4(),
        ibkr_exec_id=f"IBKR-{uuid.uuid4().hex[:8]}",
        ticker="PANW",
        direction="BUY",
        quantity=Decimal("1"),
        actual_entry=Decimal("337.10"),
        entry_date=NOW,
        planned_entry=None,
        stop_loss=None,
        target=None,
        strategy_id=None,
        thesis=None,
        # Mirrors the real column default: risk_percent is NEVER None, which is
        # exactly why it cannot be used to detect an unsized trade.
        risk_percent=Decimal("1.00"),
        risk_amount=None,
        plan_id=None,
    )
    base.update(overrides)
    return SimpleNamespace(**base)


# ---------------------------------------------------------------------------
# A plan is not an execution
# ---------------------------------------------------------------------------


def test_plan_payload_has_no_fill_price():
    """The field that forced people to invent a fill is gone.

    The old form required `price` to save anything, so recording a plan meant
    typing an execution price for a trade that had not executed. One real plan
    was saved with actual_entry equal to its take-profit for that reason.
    """
    assert "price" not in main.PlanCreate.model_fields
    assert "exit_price" not in main.PlanCreate.model_fields
    assert "execution_time" not in main.PlanCreate.model_fields


def test_a_plan_needs_only_a_ticker_and_a_side():
    """A bias is worth recording before the prices are decided."""
    plan = main.PlanCreate(ticker="nvda", direction="buy")
    assert plan.ticker == "NVDA"
    assert plan.planned_entry is None


def test_long_and_short_are_stored_as_buy_and_sell():
    """Four spellings for two concepts is how a query silently misses rows."""
    assert main.PlanCreate(ticker="X", direction="LONG").direction == "BUY"
    assert main.PlanCreate(ticker="X", direction="short").direction == "SELL"


def test_a_side_that_is_neither_is_refused():
    with pytest.raises(ValidationError):
        main.PlanCreate(ticker="X", direction="HOLD")


def test_planned_r_is_not_a_client_input():
    """It is generated by Postgres from entry, stop and target.

    Accepting it here would let the stated R disagree with the three numbers it
    claims to summarise -- which is what happens when an edit to the stop
    forgets to recompute.
    """
    assert "planned_r" not in main.PlanCreate.model_fields
    assert "planned_r" not in main.PlanUpdate.model_fields


def test_planned_r_column_is_database_generated():
    """`Computed` is what makes SQLAlchemy omit it from INSERT and UPDATE.

    Without it every write sends a value Postgres rejects outright, because a
    generated column cannot be assigned.
    """
    assert main.PlannedTrade.__table__.c.planned_r.computed is not None


# ---------------------------------------------------------------------------
# Attaching: one plan, every fill of the leg
# ---------------------------------------------------------------------------


def test_every_fill_in_the_leg_gets_the_plan():
    """An 11-fill entry is one trade, not eleven unplanned ones."""
    plan = make_plan()
    fills = [make_fill(entry_date=NOW + timedelta(seconds=i)) for i in range(11)]

    main._apply_plan_to_fills(plan, fills)

    assert all(f.plan_id == plan.id for f in fills)
    assert plan.status == main.PLAN_ATTACHED


def test_journal_values_land_on_the_earliest_fill_only():
    """Prices on one row; risk on one row above all.

    risk_amount is absolute, not per-share. Copied onto all seven fills of a
    position, anything that summed it would report seven times the risk that
    was actually taken.
    """
    plan = make_plan()
    early = make_fill(entry_date=NOW)
    late = make_fill(entry_date=NOW + timedelta(minutes=1))

    copied = main._apply_plan_to_fills(plan, [early, late])

    assert early.planned_entry == Decimal("336.00")
    assert early.stop_loss == Decimal("328.60")
    assert early.target == Decimal("345.00")
    assert early.risk_amount == Decimal("22.20")
    assert "risk_amount" in copied

    assert late.planned_entry is None
    assert late.risk_amount is None
    # ...but the link is still on both, so provenance survives whichever fill
    # FIFO later treats as the opener.
    assert late.plan_id == plan.id


def test_take_profit_lands_in_the_column_the_ledger_reads():
    """The plan calls it take_profit; the ledger has always called it target."""
    plan = make_plan()
    fill = make_fill()
    main._apply_plan_to_fills(plan, [fill])
    assert fill.target == Decimal("345.00")


def test_an_existing_value_is_never_overwritten():
    """A filled-in field was either edited by hand or copied by an earlier
    attach. Nothing distinguishes those, so the safe reading is that it is
    yours."""
    plan = make_plan()
    fill = make_fill(stop_loss=Decimal("330.00"), thesis="my own note")

    copied = main._apply_plan_to_fills(plan, [fill])

    assert fill.stop_loss == Decimal("330.00")
    assert fill.thesis == "my own note"
    assert "stop_loss" not in copied
    assert "thesis" not in copied


def test_risk_percent_rides_on_risk_amount_being_absent():
    """risk_percent carries a column default of 1.00, so it is never NULL and
    cannot tell a sized trade from an unsized one. risk_amount has no default,
    which makes it the only honest gate."""
    plan = make_plan()
    already_sized = make_fill(risk_amount=Decimal("50.00"), risk_percent=Decimal("2.00"))

    main._apply_plan_to_fills(plan, [already_sized])

    assert already_sized.risk_amount == Decimal("50.00")
    assert already_sized.risk_percent == Decimal("2.00")


def test_attaching_nothing_is_a_no_op():
    """A plan whose leg came back empty must not be marked ATTACHED."""
    plan = make_plan()
    assert main._apply_plan_to_fills(plan, []) == []
    assert plan.status == main.PLAN_OPEN


# ---------------------------------------------------------------------------
# Which plan may claim a fill
# ---------------------------------------------------------------------------


def test_a_plan_written_before_the_fill_may_claim_it():
    plan = make_plan(created_at=NOW - timedelta(hours=2))
    assert main._plan_can_claim(plan, "PANW", "BUY", NOW)


def test_a_plan_written_just_after_the_fill_may_still_claim_it():
    """Logging lag, not hindsight.

    The ordinary case this exists for: click buy, then spend a minute writing
    the plan up. 61 seconds is comfortably inside PLAN_ATTACH_GRACE and the
    exit has not happened yet, so there is no outcome the plan could be
    reacting to.
    """
    plan = make_plan(created_at=NOW + timedelta(seconds=61))
    assert main._plan_can_claim(plan, "PANW", "BUY", NOW)


def test_a_plan_written_past_the_grace_window_may_not():
    """Past PLAN_ATTACH_GRACE, a late plan cannot describe a trade that
    already happened.

    Without this bound, writing up a trade well after taking it would attach
    it to that same trade and present a reconstruction as a prior commitment
    -- flattering exactly the bias a journal exists to catch.
    """
    plan = make_plan(created_at=NOW + main.PLAN_ATTACH_GRACE + timedelta(minutes=1))
    assert not main._plan_can_claim(plan, "PANW", "BUY", NOW)


def test_the_grace_window_never_reaches_past_the_exit():
    """The grace window covers logging lag, not a trade that has resolved.

    A plan written 30 minutes after entry is ordinarily within grace -- but
    this position closed 5 minutes after entry, so by the time the plan was
    written the outcome was already on the screen. Once that is true the
    plan is a reconstruction, whatever the clock says about the grace window
    alone.
    """
    plan = make_plan(created_at=NOW + timedelta(minutes=30))
    assert not main._plan_can_claim(
        plan, "PANW", "BUY", NOW, closed_at=NOW + timedelta(minutes=5)
    )


def test_an_open_position_has_no_exit_to_bound_the_grace():
    """No closed_at means the position is still running -- nothing for a
    plan written within grace to have seen."""
    plan = make_plan(created_at=NOW + timedelta(minutes=30))
    assert main._plan_can_claim(plan, "PANW", "BUY", NOW, closed_at=None)


def test_a_plan_inside_the_grace_and_before_the_exit_claims_it():
    """The full timeline this feature was built for: entered, planned 61
    seconds later, closed hours after that."""
    plan = make_plan(created_at=NOW + timedelta(seconds=61))
    assert main._plan_can_claim(
        plan, "PANW", "BUY", NOW, closed_at=NOW + timedelta(hours=3, minutes=46)
    )


def test_a_stale_plan_stops_competing():
    """One day past the window is refused; one day inside it is not."""
    stale = make_plan(created_at=NOW - main.PLAN_ATTACH_MAX_AGE - timedelta(days=1))
    fresh = make_plan(created_at=NOW - main.PLAN_ATTACH_MAX_AGE + timedelta(days=1))
    assert not main._plan_can_claim(stale, "PANW", "BUY", NOW)
    assert main._plan_can_claim(fresh, "PANW", "BUY", NOW)


def test_the_wrong_side_is_not_a_match():
    """A plan to buy does not describe a sell, whatever the ticker."""
    plan = make_plan(direction="BUY")
    assert not main._plan_can_claim(plan, "PANW", "SELL", NOW)


def test_the_wrong_ticker_is_not_a_match():
    plan = make_plan(ticker="PANW")
    assert not main._plan_can_claim(plan, "NVDA", "BUY", NOW)


def test_a_cancelled_plan_cannot_claim_anything():
    """Cancelling is what takes a plan out of the running for incoming fills."""
    assert not main._plan_can_claim(
        make_plan(status=main.PLAN_CANCELLED), "PANW", "BUY", NOW
    )
    assert not main._plan_can_claim(
        make_plan(status=main.PLAN_ATTACHED), "PANW", "BUY", NOW
    )


# ---------------------------------------------------------------------------
# Slippage reads the same way on both sides
# ---------------------------------------------------------------------------


def test_paying_more_than_planned_is_adverse_on_a_long():
    assert main._entry_slippage("BUY", Decimal("336.00"), Decimal("337.10")) == pytest.approx(-1.10)


def test_paying_less_than_planned_is_favourable_on_a_long():
    assert main._entry_slippage("BUY", Decimal("336.00"), Decimal("335.00")) == pytest.approx(1.00)


def test_a_short_filled_higher_is_favourable():
    """The sign has to flip with the side.

    Selling short above your planned entry is a better price for the same
    trade. A raw `actual - planned` would read correctly on longs and
    backwards on every short -- and would do it quietly.
    """
    assert main._entry_slippage("SELL", Decimal("100.00"), Decimal("101.00")) == pytest.approx(1.00)
    assert main._entry_slippage("SELL", Decimal("100.00"), Decimal("99.00")) == pytest.approx(-1.00)


def test_slippage_needs_both_numbers():
    """An unplanned trade has no slippage -- zero would be a claim."""
    assert main._entry_slippage("BUY", None, Decimal("337.10")) is None
    assert main._entry_slippage("BUY", Decimal("336.00"), None) is None


# ---------------------------------------------------------------------------
# The ledger stays broker-owned
# ---------------------------------------------------------------------------


def test_hand_added_fills_are_labelled_not_hidden():
    """A hand-typed price is an assertion and should look like one next to
    figures the broker vouched for."""
    assert main.EXEC_PREFIX_REPAIR == "REPAIR-"
    assert main.EXEC_PREFIX_BROKER == "IBKR-"
    assert "has_hand_added_fills" in main.RoundTripOut.model_fields


def test_the_sync_reports_plans_it_attached():
    """The moment the two halves of the journal meet is worth a line."""
    result = main.IngestResult(
        executions_parsed=3, staged_new=3, staged_duplicates=0,
        trades_created=3, trades_duplicates=0, positions_matched=0,
        symbols_touched=["PANW"], skipped_non_tradeable=0, plans_attached=1,
    )
    assert result.plans_attached == 1


def test_plans_attached_defaults_to_zero():
    """Older callers constructing a result without it must not break."""
    result = main.IngestResult(
        executions_parsed=0, staged_new=0, staged_duplicates=0,
        trades_created=0, trades_duplicates=0, positions_matched=0,
        symbols_touched=[], skipped_non_tradeable=0,
    )
    assert result.plans_attached == 0


# ---------------------------------------------------------------------------
# Editing rules
# ---------------------------------------------------------------------------


def test_a_plan_cannot_be_talked_into_attached_status():
    """ATTACHED is reached by attaching to a real fill, never by assertion --
    otherwise a plan could claim a trade that does not point back at it."""
    with pytest.raises(ValidationError, match="attach a plan to a trade"):
        main.PlanUpdate(status="attached")


def test_the_two_settable_statuses_are_accepted():
    """Cancelling and re-opening are the client's to choose."""
    assert main.PlanUpdate(status="cancelled").status == main.PLAN_CANCELLED
    assert main.PlanUpdate(status="open").status == main.PLAN_OPEN


def test_an_unknown_status_is_refused_at_the_edge():
    with pytest.raises(ValidationError):
        main.PlanUpdate(status="ARCHIVED")


def test_partial_edits_do_not_blank_untouched_fields():
    """exclude_unset is what separates 'set this to null' from 'left alone'."""
    changes = main.PlanUpdate(thesis="revised").model_dump(exclude_unset=True)
    assert changes == {"thesis": "revised"}
